language: cpp

os:
  - linux
  - osx

matrix:
  exclude:
  - os: linux
  include:
  - os: linux
    env: COMP=clang++-3.7
    addons:
      apt:
        packages:
          - clang-3.7
          - tcl
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7

  - os: linux
    env: COMP=clang++-3.5
    addons:
      apt:
        packages:
          - clang-3.5
          - tcl
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.5

  - os: linux
    env: COMP=g++-5
    addons:
      apt:
        packages:
          - g++-5
          - tcl
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test

  - os: linux
    env: COMP=g++-4.9
    addons:
      apt:
        packages:
          - g++-4.9
          - tcl
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test

script:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then LINUX_ONLY="COMPILE=${COMP} LINK=${COMP}"; fi
  - if [ "${COMP}" == "clang++-3.7" ]; then scan-build-3.7 ${COMP} -std=c++11 -c -Wall -DASSERTIONS -DSPELLCHKVALIDATE -I/usr/include/tcl src/*.cpp src/polyglot/*.cpp; fi
  - ./configure ${LINUX_ONLY} && make && size tkscid
  - make clean
  - ./configure ${LINUX_ONLY} THREADS="" && make && size tkscid
  - make clean
  - ./configure ${LINUX_ONLY} DEBUG="-DASSERTIONS -DSPELLCHKVALIDATE" && make && size tkscid
