language: cpp

os:
  - linux
  - osx

matrix:
  exclude:
  - os: linux
  include:
  - os: linux
    env: COMP=clang++-3.7
    addons:
      apt:
        packages:
          - clang-3.7
          - tcl
          - tcl-dev
          - tk
          - cloc
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7

  - os: linux
    env: COMP=clang++-3.5
    addons:
      apt:
        packages:
          - clang-3.5
          - tcl
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.5

  - os: linux
    env: COMP=g++-5
    addons:
      apt:
        packages:
          - g++-5
          - tcl
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test

  - os: linux
    env: COMP=g++-4.9
    addons:
      apt:
        packages:
          - g++-4.9
          - tcl
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test


before_install:
 - git clone https://github.com/google/googletest.git googletest
 - cd googletest
 - cmake CMakeLists.txt
 - make
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo mv googletest/include/gtest /usr/include && sudo cp googlemock/gtest/*.a /usr/lib; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo mv googlemock/include/gmock /usr/include && sudo cp googlemock/*.a /usr/lib; fi
 - cd $TRAVIS_BUILD_DIR


script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then LINUX_ONLY="COMPILE=${COMP} LINK=${COMP}"; fi
  - if [ "${COMP}" == "clang++-3.7" ]; then cloc src --exclude-dir=egtb,mtbgen,polyglot; fi
  - if [ "${COMP}" == "clang++-3.7" ]; then cloc tcl --exclude-dir=lang; fi
  - if [ "${COMP}" == "clang++-3.7" ]; then scan-build-3.7 ${COMP} -std=c++11 -c -Wall -DASSERTIONS -DSPELLCHKVALIDATE -I/usr/include/tcl src/*.cpp src/polyglot/*.cpp; fi
  - if [ "${COMP}" == "g++-5" ]; then ./configure COMPILE="${COMP}" LINK="${COMP}" && make test && make clean; fi
  - ./configure ${LINUX_ONLY} && make && size tkscid
  - make clean
  - ./configure ${LINUX_ONLY} THREADS="" && make && size tkscid
  - make clean
  - ./configure ${LINUX_ONLY} DEBUG="-DASSERTIONS -DSPELLCHKVALIDATE" && make && size tkscid
