language: cpp

os:
  - linux

matrix:
  include:
  - os: linux
    env: COMP=clang++-3.7
    addons:
      apt:
        packages:
          - clang-3.7
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise

  - os: linux
    env: COMP=clang++-3.5
    addons:
      apt:
        packages:
          - clang-3.5
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.5

  - os: linux
    env: COMP=g++-5
    addons:
      apt:
        packages:
          - g++-5
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test

  - os: linux
    env: COMP=g++-4.9
    addons:
      apt:
        packages:
          - g++-4.9
          - tcl-dev
          - tk
        sources:
          - ubuntu-toolchain-r-test


script:
  - if [ "${COMP}" == "clang++-3.7" ]; then scan-build-3.7 ${COMP} -std=c++11 -c -Wall -DASSERTIONS -DSPELLCHKVALIDATE -I/usr/include/tcl src/*.cpp src/polyglot/*.cpp; fi
  - ./configure COMPILE="${COMP}" LINK="${COMP}" && make
  - make clean
  - ./configure COMPILE="${COMP}" LINK="${COMP}" THREADS="" && make
  - make clean
  - ./configure COMPILE="${COMP}" LINK="${COMP}" DEBUG="-DASSERTIONS -DSPELLCHKVALIDATE" && make
