dist: trusty
sudo: false

os:
  - linux
  - osx

matrix:
  exclude:
  - os: linux
  - os: osx
  include:
  - os: osx
    env: CXX=c++

  - os: linux
    env: CXX=clang++-4.0 CC=clang-4.0
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - libstdc++-6-dev
          - tcl
          - tcl-dev
          - cloc

  - os: linux
    env: CXX=g++-6 CC=gcc-6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - tcl
          - tcl-dev
          - cloc

  - os: linux
    env: CXX=g++-4.9 CC=gcc-4.9
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
          - tcl
          - tcl-dev
          - cloc

script:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cloc src --exclude-dir=egtb,mtbgen,polyglot; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cloc tcl --exclude-dir=lang; fi
  - cd $TRAVIS_BUILD_DIR
  - if [ "${CXX}" == "clang++-4.0" ]; then mkdir Analyzer && cd Analyzer && scan-build-4.0 cmake .. && scan-build-4.0 make scid; fi
  - cd $TRAVIS_BUILD_DIR
  - mkdir Debug && cd Debug && cmake .. -DCMAKE_BUILD_TYPE=Debug && make
  - cd $TRAVIS_BUILD_DIR
  - mkdir Testing && cd Testing && cmake ../gtest && make && ./runAll
  - cd $TRAVIS_BUILD_DIR
  - mkdir Release && cd Release && cmake .. && make VERBOSE=1 && size scid
  - cd $TRAVIS_BUILD_DIR
  - ./configure && make && size tkscid
  - make clean
  - ./configure THREADS="-std=c++98" && make && size tkscid
  - make clean
  - ./configure DEBUG="-g -DSPELLCHKVALIDATE" && make && size tkscid

