dist: trusty
sudo: false

os:
  - linux
  - osx

matrix:
  exclude:
  - os: linux
  - os: osx
  include:
  - os: osx
    env: CXX=c++

  - os: linux
    env: CXX=clang++-5.0 CC=clang-5.0
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
          - clang-tidy-5.0
          - libstdc++-6-dev
          - tcl
          - tcl-dev
          - cloc

  - os: linux
    env: CXX=g++-7 CC=gcc-7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - tcl
          - tcl-dev
          - cloc

  - os: linux
    env: CXX=g++-7 CC=gcc-7 SCID_TH="-DSCID_MULTITHREADING=OFF"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - tcl
          - tcl-dev
          - cloc

  - os: linux
    env: CXX=g++-4.9 CC=gcc-4.9
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
          - tcl
          - tcl-dev
          - cloc

script:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cloc src --exclude-dir=egtb,mtbgen,polyglot; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cloc tcl --exclude-dir=lang; fi
  - cd $TRAVIS_BUILD_DIR
  - if [ "${CXX}" != "g++-4.9" ]; then
      mkdir Debug && cd Debug && cmake .. -DCMAKE_BUILD_TYPE=Debug -DSPELLCHKVALIDATE=ON $SCID_TH && make;
    else
      mkdir Debug && cd Debug && cmake .. -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror" -DSPELLCHKVALIDATE=ON $SCID_TH && make;
    fi
  - if [ "${CXX}" == "clang++-5.0" ]; then run-clang-tidy-5.0.py -header-filter=.* -checks=clang-*,-clang-analyzer-security.insecureAPI.strcpy ../src; fi
  - cd $TRAVIS_BUILD_DIR
  - mkdir Testing && cd Testing
  - if [ "${CXX}" == "clang++-5.0" ]; then
      cmake ../gtest/ -DCMAKE_CXX_FLAGS="-g -O3 -Wall -Wextra -Werror -fsanitize=address,undefined,integer" $SCID_TH;
    else
      if [ "${CXX}" == "g++-7" ]; then
        cmake ../gtest/ -DCMAKE_CXX_FLAGS="-g -O3 -Wall -Wextra -Werror -fsanitize=thread,undefined -fuse-ld=gold" $SCID_TH;
      else
        cmake ../gtest;
      fi
    fi
  - make VERBOSE=1 && ./scid_tests
  - cd $TRAVIS_BUILD_DIR
  - mkdir Release && cd Release && cmake .. $SCID_TH && make VERBOSE=1 && size scid
  - cd $TRAVIS_BUILD_DIR
  - if [ "${SCID_TH}" == "-DSCID_MULTITHREADING=OFF" ]; then
      ./configure COMPILE="${CXX}" THREADS="-DMULTITHREADING_OFF" && make && size tkscid;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ./configure COMPILE="${CXX}" && make && size tkscid;
    else
      ./configure && make && size tkscid;
    fi
