language: cpp

os:
  - linux
  - osx

matrix:
  exclude:
  - os: linux
  - os: osx
  include:
  - os: osx
    env: COMP=c++

  - os: linux
    env: COMP=clang++-3.8
    addons:
      apt:
        packages:
          - clang-3.8
          - tcl
          - tcl-dev
          - tk
          - cloc
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8

  - os: linux
    env: COMP=g++-6
    addons:
      apt:
        packages:
          - g++-6
          - tcl
          - tcl-dev
          - tk
          - cloc
        sources:
          - ubuntu-toolchain-r-test

  - os: linux
    env: COMP=g++-4.9
    addons:
      apt:
        packages:
          - g++-4.9
          - tcl
          - tcl-dev
          - tk
          - cloc
        sources:
          - ubuntu-toolchain-r-test


before_install:
 - git clone https://github.com/google/googletest.git googletest
 - cd googletest
 - cmake . && make
 - sudo cp -a googletest/include/gtest /usr/local/include
 - sudo cp -a googlemock/gtest/*.a /usr/local/lib
 - sudo cp -a googlemock/include/gmock /usr/local/include
 - sudo cp -a googlemock/*.a /usr/local/lib
 - cd $TRAVIS_BUILD_DIR


script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then LINUX_ONLY="COMPILE=${COMP} LINK=${COMP}"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cloc src --exclude-dir=egtb,mtbgen,polyglot; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cloc tcl --exclude-dir=lang; fi
  - if [ "${COMP}" == "clang++-3.8" ]; then scan-build-3.8 ${COMP} -std=c++11 -c -Wall -DSPELLCHKVALIDATE -I/usr/include/tcl src/*.cpp; fi
  - cd $TRAVIS_BUILD_DIR
  - mkdir Debug && cd Debug && cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER="${COMP}" && make
  - cd $TRAVIS_BUILD_DIR
  - mkdir Testing && cd Testing && cmake ../gtest -DCMAKE_CXX_COMPILER="${COMP}" && make
  - cd $TRAVIS_BUILD_DIR/gtest && ./runAll
  - cd $TRAVIS_BUILD_DIR
  - mkdir Release && cd Release && cmake .. -DCMAKE_CXX_COMPILER="${COMP}" && make VERBOSE=1 && size scid
  - cd $TRAVIS_BUILD_DIR
  - ./configure ${LINUX_ONLY} && make && size tkscid
  - make clean
  - ./configure ${LINUX_ONLY} THREADS="" && make && size tkscid
  - make clean
  - ./configure ${LINUX_ONLY} DEBUG="-g -DSPELLCHKVALIDATE" && make && size tkscid
